#!/bin/bash

INPUT_FILE=$1
COMMENT=`head -n1 $INPUT_FILE`
BRANCH_NAME=$(git branch | grep -P "\*" | sed -r "s/\*\s//")

check_message() {
 if [[ ! "$1" =~ $2 ]]; then
    echo "\tNão é possível fazer esse tipo de commit nessa branch. Apenas com prefixo \033[1m$3"
    exit 1
  fi
  exit 0
}

if [[ ! "${BRANCH_NAME}" =~ ^(feature|hotfix|cloud) ]]; then
  echo -e "\tNão é possível commitar nessa branch \033[1m${BRANCH_NAME}"
  exit 1
fi


if   [[ "${BRANCH_NAME}" =~ ^feat ]]; then
 check_message "${COMMENT}" "^(feat|doc|test)" "feat, doc e test" 
elif [[ "${BRANCH_NAME}" =~ ^fix ]]; then
 check_message "${COMMENT}" "^fix" "fix"
elif [[ "${BRANCH_NAME}" =~ ^cloud ]]; then
 check_message "${COMMENT}" "^chore" "chore"
fi

exit 1
