#!/bin/bash

INPUT_FILE=$1
COMMENT=`head -n1 $INPUT_FILE`
BRANCH_NAME=$(git branch | grep -P "\*" | sed -r "s/\*\s//")

check_message() {
  if [[ -z $(echo $1 | grep -Po $2) ]]; then
    echo -e "\tNão é possível fazer esse tipo de commit nessa branch. Apenas com prefixo \033[1m$3"
    exit 1
  fi
  exit 0
}

if [[ -z $(echo ${BRANCH_NAME} | grep -Po "^(feature|(bug|hot)?fix|cloud|refact|test)") ]]; then
  echo -e "\tNão é possível commitar nessa branch \033[1m${BRANCH_NAME}"
  exit 1
fi

if   [[ -n $(echo ${BRANCH_NAME} | grep -Po "^(feat|doc|test|refact)") ]]; then
 check_message "${COMMENT}" "^(feat|doc|test|refact)" "feat, refact, doc e test" 
elif [[ -n $(echo ${BRANCH_NAME} | grep -Po "^(hot|bug)?fix") ]]; then
 check_message "${COMMENT}" "^fix" "fix"
elif [[ -n $(echo ${BRANCH_NAME} | grep -Po "^cloud") ]]; then
 check_message "${COMMENT}" "^chore" "chore"
fi

exit 1
